### ISSUE TITLE
Error when building Caddy through Dockerfile with Namesilo module

### ISSUE THREAD

**Issue by RockBrackenshield** [caddy-dns/namesilo#3]
Hello,

I'm working on setting up a Caddy through Docker to use in my local network, and upon running the xcaddy command to build caddy with this module included, it unfortunately errored out. The actual error and output is below:

```
[INFO] exec (timeout=0s): /usr/local/go/bin/go build -o /usr/bin/caddy -ldflags -w -s -trimpath -tags nobadger
# github.com/libdns/namesilo
/go/pkg/mod/github.com/libdns/namesilo@v.0.1.0/provider.go:69:14: cannot use record.Priority (variable of type int) as uint value in struct literal
[INFO] Skipping cleanup as requested; leaving folder intact: /tmp/buildenv_2024_07_10-1343.2734633133
[FATAL] exit status 1
------
failed to solve: process "/bin/sh -c xcaddy build --with github.com/caddy-dns/namesilo" did not complete successfully: exit code: 1
```

As for the Dockerfile I'm using, I've included it below if that's of help as well

```
FROM caddy:2.8.4-builder AS builder
RUN xcaddy build --with github.com/caddy-dns/namesilo

FROM caddy:2.8.4

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

**Comment by RockBrackenshield** [comment]
Taking a look at the libdns/namesilo repository, it looks like this may have been fixed in libdns/namesilo@v.0.1.1, if you know of a way you know of forcing this module to use libdns/namesilo v.0.1.1 rather than v.0.1.0, that would be great.

**Comment by WeidiDeng** [comment]
You can use this Dockerfile:

```
FROM caddy:2.8.4-builder AS builder
RUN xcaddy build --with github.com/caddy-dns/namesilo --with github.com/libdns/namesilo@v0.1.1

FROM caddy:2.8.4

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

to specify the version of the dependency.

I'll update the go.mod file shortly 😅 so that this is no longer needed.
